# fly.toml app configuration file generated for personal-site-still-snowflake-1 on 2024-12-05T04:19:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personal-site-still-snowflake-1"
primary_region = "yyz"

[http_service]
auto_start_machines = true
auto_stop_machines = "off"
force_https = true
internal_port = 3_000
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
memory_mb = 512
processes = [ "app" ]
size = "shared-cpu-1x"